site_name: QuAntiL
repo_url: https://github.com/UST-QuAntiL/quantil-docs
edit_uri: tree/master/docs
nav:
    - User Guide:
        - 'Overview': 'user-guide/overview.md'
        - 'Algorithm': 'user-guide/algorithm.md'
        - 'Implementation': 'user-guide/implementation.md'
        - 'Publication': 'user-guide/publication.md'
        - 'Cloud Service': 'user-guide/execution-environments/cloud-service.md'
        - 'Compute Ressource': 'user-guide/execution-environments/compute-ressource.md'
        - 'Software Platform': 'user-guide/execution-environments/software-platform.md'
        - 'Application Area': 'user-guide/application-area.md'
        - 'Problem Type': 'user-guide/problem-type.md'
        - 'Algorithm Relation Type': 'user-guide/algorithm-relation-type.md'
        - 'Pattern Relation Type': 'user-guide/pattern-relation-type.md'
        - 'Compute Resource Property Type': 'user-guide/compute-resource-property-type.md'
        - 'NISQ Analyzer': 'user-guide/nisq-analyzer.md'
        - 'QProv': 'user-guide/qprov.md'
    - Developer Guide:
        - 'Docker': 'developer-guide/docker.md'
        - 'IntelliJ Setup': 'developer-guide/intellij.md'
        - 'OpenAPI': 'developer-guide/openapi.md'
        - 'Application Architecture': developer-guide/qc-atlas/application-architecture.md
        - 'Latex Renderer': developer-guide/qc-atlas/latex-renderer.md
        - 'Testing': developer-guide/qc-atlas/testing.md
        - 'Database migrations': 'developer-guide/qc-atlas/db-migrations.md'
theme: readthedocs
extra_css:
    - css/extra.css
markdown_extensions:
    - admonition
    - attr_list
