site_name: QuAntiL
nav:
    - Getting Started:
        - 'Setup': 'getting-started/getting-started.md'
    - User Guide:
        - 'Overview': 'user-guide/overview.md'
        - 'Algorithm': 'user-guide/algorithm.md'
        - 'Implementation': 'user-guide/implementation.md'
        - 'Publication': 'user-guide/publication.md'
        - 'Cloud Service': 'user-guide/execution-environments/cloud-service.md'
        - 'Compute Ressource': 'user-guide/execution-environments/compute-ressource.md'
        - 'Software Platform': 'user-guide/execution-environments/software-platform.md'
    - Developer Guide:
        - 'OpenAPI': 'developer-guide/openapi.md'
        - QC-Atlas Backend:
            - 'Application Architecture': developer-guide/qc-atlas/application-architecture.md
            - 'Testing': developer-guide/qc-atlas/testing.md
        - 'IntelliJ Setup': 'developer-guide/intellij.md'
theme: readthedocs
extra_css:
    - css/extra.css
markdown_extensions:
    - admonition
    - attr_list 
