name: GitHub Pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt
          mkdocs build
